### ISSUE TITLE
First Release

### ISSUE THREAD

**Issue by jarreds** [sluongng/nogo-analyzer#1]
Thanks for the work on this! Any ETA on cutting a first release?

**Comment by sluongng** [comment]
Hmm I should be able to cut a release within this week for the `staticcheck` portion of the repo, which I think is fairly stable baring some niche use cases that might require a fix in `rules_go`. I was hoping to be able to create some project-keeping mechanism before the first release but I think those can wait until later.

Thanks for reminding me on this.

**Comment by mattforbes-gr** [comment]
+1 

just found this repo. thanks for putting this together

**Comment by sluongng** [comment]
I cut an intial release here https://github.com/sluongng/nogo-analyzer/releases/tag/v0.0.1

Please try it out and let me know if there is any issues.

In the up coming days, I will spend sometimes creating a backlog of todo items for this projects. Hopefully it would help highlighting known issues and items I want to address in the near future.
