### ISSUE TITLE
Add govulncheck linter

### ISSUE THREAD

**Issue by malt3** [sluongng/nogo-analyzer#32]
This is a feature idea / request.
First of all: thank you so much for working on this!
Having cached / incremental linters for Bazel / Go would greatly improve the velocity of my team.
Especially if this can be done in CI.

I wonder if [govulncheck](https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck) could be adapted to be a nogo-analyzer.
Since govulncheck is very resource intensive, it would greatly benefit from nogo support.
I don't currently understand nogo or govulncheck well enough to understand fully if they could work together, so feel free to close this if it is not feasible.

**Comment by sluongng** [comment]
`govulncheck` is a complicated tool. It does not use the typical `Analyzer` framework and requires a constantly updated db of known vulnerabilities.

I have commented in https://github.com/golang/go/issues/61494#issuecomment-2173789704 wrt how it could be supported in the Bazel ecosystem. But if that ever happens, we would want a separate rule for it and not in `nogo-analyzer.git` repo.
